-- CREATE DATABASE g30db;
-- DROP DATABASE g30db;
USE g30db;
-- DROP TABLE customers, items;

CREATE TABLE customers(
	CUSTOMERID		INTEGER			PRIMARY KEY,
    CUSTOMERNAME	VARCHAR(50),
    CUSTOMERMONEY	DECIMAL(9,2)
);
CREATE TABLE items(
	ITEMID			INTEGER			PRIMARY KEY,
    ITEMNAME		VARCHAR(30),
    ITEMPRICE		DECIMAL(9,2),
    ITEMAMOUNT		INTEGER,
    ITEMDESC		VARCHAR(400)
);

SHOW TABLES;
SELECT * FROM customers;
SELECT * FROM items;
